#!/bin/bash
#gtk setting, could be modified by lxappearance 
export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

xrdb -merge .Xresources

#backgroud image setting
nitrogen --restore &

#start dropbox 
dropbox start &

# Remap caps lock to left control
setxkbmap -option 'ctrl:nocaps'

# start xmonad
exec .cabal/bin/xmonad

