#!/bin/bash

#start gnome
gnome-settings-daemon &

#gtk setting, could be modified by lxappearance 
#export GTK2_RC_FILES="$HOME/.gtkrc-2.0"

#xrdb -merge .Xresources

#backgroud image setting
nitrogen --restore &

#start dropbox 
dropbox start &

#start synapse 
synapse &

#start emacs
emacs-snapshot &

# Remap caps lock to left control, it is no need because of gnome-setting-daemon.
#setxkbmap -option 'ctrl:nocaps'

# start xmonad
exec .cabal/bin/xmonad

